config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  scope 'modes' do
    root               to: 'modes#index',   as: :modes
    get    'new',      to: 'modes#new',     as: :new_mode
    post   'new',      to: 'modes#create',  as: :create_mode
    get    ':id/edit', to: 'modes#edit',    as: :edit_mode
    patch  ':id/edit', to: 'modes#update',  as: :update_mode
    delete ':id',      to: 'modes#destroy', as: :destroy_mode
  end

  scope 'lines' do
    root               to: 'lines#index',   as: :lines
    get    'new',      to: 'lines#new',     as: :new_line
    post   'new',      to: 'lines#create',  as: :create_line
    get    ':id',      to: 'lines#show',    as: :line
    get    ':id/edit', to: 'lines#edit',    as: :edit_line
    patch  ':id/edit', to: 'lines#update',  as: :update_line
    delete ':id',      to: 'lines#destroy', as: :destroy_line
  end

  scope 'stops' do
    post   'new',      to: 'stops#create',  as: :new_stop
    post   ':id/move', to: 'stops#move',    as: :move_stop
    post   'clone',    to: 'stops#clone',   as: :clone_stops
    delete 'location', to: 'stops#destroy', as: :destroy_stop
  end

  scope 'points' do
    post   'new',      to: 'routing_points#create',  as: :new_point
    delete 'location', to: 'routing_points#destroy', as: :destroy_point
  end

  scope 'connections' do
    post   ':id/change', to: 'connections#toggle_change', as: :toggle_connection_change
    delete ':id',        to: 'connections#destroy',       as: :destroy_connection
  end
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :mode
  has_many :stops
  has_many :routing_points
  has_many :connections_out, class_name: 'Connection', foreign_key: :from_id
  has_many :connections_in, class_name: 'Connection', foreign_key: :to_id

  def connections
    Connection.where(id: connections_out.map(&:id) + connections_in.map(&:id))
  end

  def generate_connections
    stops.each do |s|
      s.lines.each do |l|
        next if l == self
        next if Connection.where(stop: s, from: self, to: l).or(Connection.where(stop: s, from: l, to: s)).exist?

        Connection.create(stop: s, from: self, to: l, change_required: true)
      end
    end
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :require_admin, except: [:show]
  before_action :set_line, except: [:index, :new, :create, :show]

  def index
    @lines = Line.all.includes(:mode).includes(:stops).includes(:routing_points).paginate(page: params[:page], per_page: 21)
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.new line_params
    if @line.save
      flash[:success] = 'Line saved.'
      redirect_to line_path(@line)
    else
      flash[:danger] = 'Failed to save line.'
      render :new
    end
  end

  def show
    @line = Line.where(id: params[:id]).includes(:mode, connections_in: [:from, :to, :stop], connections_out: [:from, :to, :stop]).first
    @directions = @line.stops.select('DISTINCT direction')
    @stops = @directions.map { |d| [d.direction, @line.stops.where(direction: d.direction).order(:index)] }.to_h
  end

  def edit; end

  def update
    if @line.update line_params
      flash[:success] = 'Line saved.'
      redirect_to line_path(@line)
    else
      flash[:danger] = 'Failed to save line.'
      render :edit
    end
  end

  def destroy
    if @line.destroy
      flash[:success] = 'Removed line.'
    else
      flash[:danger] = 'Failed to remove line.'
    end
    redirect_to lines_path
  end

  private

  def set_line
    @line = Line.find params[:id]
  end

  def line_params
    params.require(:line).permit(:mode_id, :name, :description)
  end
end

app/views/lines/_edit_route.html.erb
<h2>Edit Route &amp; Stops</h2>
<div class="line-full-map" data-id="<%= line.id %>"></div><br/>
<div class="clearfix">
  <div class="btn-group pull-left">
    <a href="#" class="btn btn-primary edit-line-toggle" data-mode="route"><i class="fa fa-fw fa-location-arrow"></i> Edit Route</a>
    <a href="#" class="btn btn-primary edit-line-toggle" data-mode="stops"><i class="fa fa-fw fa-map-marker"></i> Edit Stops</a>
  </div>
  <div class="form-group pull-left">
    <div class="input-group direction-group">
      <span class="input-group-addon">Stop direction:</span>
      <datalist id="stop_directions">
        <option value="Outbound"></option>
        <option value="Return"></option>
      </datalist>
      <input name="stop_direction" id="stop_direction" list="stop_directions" type="text" class="form-control" />
    </div>
    <div class="help-block">
      Please enter a direction before creating stops.
    </div>
  </div>
</div>
<div class="help-block">
  <p>
    <i class="fa fa-fw fa-location-arrow"></i> <strong>Route Mode</strong> - Click to add a point to the route. Click on a point to delete it.
    Draw a line that follows the route of the line.
  </p>
  <p><i class="fa fa-fw fa-map-marker"></i> <strong>Stops Mode</strong> - Click to add a stop. Click on a stop to delete it.</p>
</div>

app/views/lines/_form.html.erb
<%= form_for @line, url: url do |f| %>
  <div class="field">
    <%= f.label :mode_id, 'Mode' %><br/>
    <%= f.select :mode_id, options_from_collection_for_select(Mode.all, 'id', 'name', selected: @line.mode_id),
                 { include_blank: true }, class: 'form-control select2' %>
  </div><br/>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class: 'form-control' %>
  </div><br/>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description, rows: 5, cols: 100, class: 'form-control' %>
  </div><br/>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/lines/_json.html.erb
<script>
  let linesData = <%= raw(lines.map { |l| [l.id, { stops: l.stops.map(&:as_json), routing_points: l.routing_points.map(&:as_json) }] }
                                .to_h.to_json) %>;
  Object.globalAssign('mapt', { linesData });
</script>

app/views/lines/_line.html.erb
<div class="col-md-4">
  <div class="panel panel-default line-panel" data-id="<%= line.id %>">
    <div class="panel-body">
      <div class="clearfix">
        <h4 class="pull-left">
          <%= link_to line_path(line) do %>
            <i class="fa fa-<%= line.mode.icon %>"></i> <%= line.name %>
          <% end %>
        </h4>
        <% if current_user&.has_role?(:admin) %>
          <h4 class="pull-right">
            <%= link_to edit_line_path(line) do %>
              <i class="fa fa-fw fa-pencil"></i>
            <% end %>
            <%= link_to destroy_line_path(line), method: :delete, class: 'text-danger' do %>
              <i class="fa fa-fw fa-times"></i>
            <% end %>
          </h4>
        <% end %>
      </div>
      <div class="line-condensed-map"></div><br/>
      <p><%= line.description %></p>
    </div>
  </div>
</div>

app/views/lines/edit.html.erb
<h1>Edit Line <%= @line.name %></h1>
<p><%= link_to raw('&larr; Back to list'), lines_path %></p>
<%= render 'form', url: update_line_path(@line) %>
<%= render 'edit_route', line: @line %>
<%= render 'json', lines: [@line] %>
<%= marker_paths %>
<%= maps_javascript 'mapt.initRouteEditMap' %>

app/views/lines/index.html.erb
<h1>Lines</h1>
<% if current_user&.has_role?(:admin) %>
  <p>
    <%= link_to '+ Add new', new_line_path %>
  </p>
<% end %>

<% @lines.in_groups_of(3).map(&:compact).each do |g| %>
  <div class="row">
    <% g.each do |l| %>
      <%= render 'line', line: l %>
    <% end %>
  </div>
<% end %>

<%= render 'json', lines: @lines %>

<%= marker_paths %>
<%= maps_javascript 'mapt.initLinesIndexMaps' %>

app/views/lines/new.html.erb
<h1>New Line</h1>
<%= render 'form', url: create_line_path %>

app/views/lines/show.html.erb
<h1>
  <i class="fa fa-<%= @line.mode.icon %>"></i> <%= @line.name %>
  <% if current_user&.has_role?(:admin) %>
    <small>
      <%= link_to edit_line_path(@line) do %>
        <i class="fa fa-fw fa-pencil"></i>
      <% end %>
      <%= link_to destroy_line_path(@line), method: :delete, class: 'text-danger' do %>
        <i class="fa fa-fw fa-times"></i>
      <% end %>
    </small>
  <% end %>
</h1>
<p><%= @line.description %></p>
<div class="line-full-map" data-id="<%= @line.id %>"></div>

<h2>Stops on this line</h2>
<% @directions.in_groups_of(2).map(&:compact).each do |g| %>
  <% admin = current_user&.has_role?(:admin) %>
  <div class="row">
    <% g.each_with_index do |d, i| %>
      <div class="<%= @directions.size < 2 && i == 0 ? 'col-md-5' : 'col-md-6' %>">
        <%= render 'stops/line_table', stops: @stops[d.direction], direction: d.direction, admin: admin %>
      </div>
      <% if @directions.size < 2 && i == 0 %>
        <div class="col-md-2 text-center clone-controls">
          <%= link_to clone_stops_path(line_id: @line.id), method: :post, title: 'Clone stops list to opposite direction' do %>
            <i class="fa fa-2x fa-clone"></i>
            <p>Clone</p>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

<h2>Connections</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Connects to</th>
      <th>At</th>
      <th>Change required? <span class="text-muted">click to toggle</span></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @line.connections.each do |c| %>
      <% l = c.other_line(@line) %>
      <tr>
        <td>
          <%= link_to line_path(l) do %>
            <i class="fa fa-fw fa-<%= l.mode.icon %>"></i> <%= l.name %>
          <% end %>
        </td>
        <td><%= c.stop.name %></td>
        <td>
          <%= link_to toggle_connection_change_path(c), method: :post, class: "text-#{c.change_required? ? 'success' : 'danger'} toggle-change",
                      remote: true do %>
            <i class="fa fa-<%= c.change_required? ? 'check' : 'times' %>"></i>
          <% end %>
        </td>
        <td class="text-right">
          <% if current_user&.has_role?(:admin) %>
            <%= link_to destroy_connection_path(c), method: :delete, class: 'text-danger delete-connection', remote: true,
                        data: { toggle: 'tooltip' }, title: 'delete' do %>
              <i class="fa fa-times"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'json', lines: [@line] %>

<%= marker_paths %>
<%= maps_javascript 'mapt.initLineShowMap' %>