config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  scope 'modes' do
    root               to: 'modes#index',   as: :modes
    get    'new',      to: 'modes#new',     as: :new_mode
    post   'new',      to: 'modes#create',  as: :create_mode
    get    ':id/edit', to: 'modes#edit',    as: :edit_mode
    patch  ':id/edit', to: 'modes#update',  as: :update_mode
    delete ':id',      to: 'modes#destroy', as: :destroy_mode
  end

  scope 'lines' do
    root               to: 'lines#index',   as: :lines
    get    'new',      to: 'lines#new',     as: :new_line
    post   'new',      to: 'lines#create',  as: :create_line
    get    ':id',      to: 'lines#show',    as: :line
    get    ':id/edit', to: 'lines#edit',    as: :edit_line
    patch  ':id/edit', to: 'lines#update',  as: :update_line
    delete ':id',      to: 'lines#destroy', as: :destroy_line
  end

  scope 'stops' do
    post   'new',      to: 'stops#create',  as: :new_stop
    post   ':id/move', to: 'stops#move',    as: :move_stop
    post   'clone',    to: 'stops#clone',   as: :clone_stops
    delete 'location', to: 'stops#destroy', as: :destroy_stop
  end

  scope 'points' do
    post   'new',      to: 'routing_points#create',  as: :new_point
    delete 'location', to: 'routing_points#destroy', as: :destroy_point
  end

  scope 'connections' do
    post   ':id/change', to: 'connections#toggle_change', as: :toggle_connection_change
    delete ':id',        to: 'connections#destroy',       as: :destroy_connection
  end
end

app/models/mode.rb
class Mode < ApplicationRecord
  has_many :routes
end

app/controllers/modes_controller.rb
class ModesController < ApplicationController
  before_action :require_admin, except: [:index]
  before_action :set_mode, only: [:edit, :update, :destroy]

  def index
    @modes = Mode.all.paginate(page: params[:page], per_page: 15)
  end

  def new
    @mode = Mode.new
  end

  def create
    @mode = Mode.new mode_params
    if @mode.save
      flash[:success] = 'Created travel mode.'
      redirect_to modes_path
    else
      flash[:danger] = 'Failed to save travel mode.'
      render :new
    end
  end

  def edit; end

  def update
    if @mode.update mode_params
      flash[:success] = 'Updated travel mode successfully.'
      redirect_to modes_path
    else
      flash[:danger] = 'Failed to save travel mode.'
      render :edit
    end
  end

  def destroy
    if @mode.destroy
      flash[:success] = 'Removed travel mode.'
      success = true
    else
      flash[:danger] = 'Failed to remove travel mode.'
      success = false
    end
    render json: { success: success }, status: success ? 200 : 500
  end

  private

  def mode_params
    params.require(:mode).permit(:name, :description, :icon)
  end

  def set_mode
    @mode = Mode.find params[:id]
  end
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/views/modes/_form.html.erb
<%= form_for @mode, url: url do |f| %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class: 'form-control' %>
  </div><br/>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description, rows: 5, cols: 100, class: 'form-control' %>
  </div><br/>

  <div class="field">
    <%= f.label :icon %><br/>
    <div class="input-group">
      <span class="input-group-addon"><i id="mode-icon-selector" class="fa fa-spinner"></i></span>
      <%= f.text_field :icon, class: 'form-control', id: 'mode-icon-input' %>
    </div>
    <span class="help-block">Icons from <a href="http://fontawesome.io/icons">FontAwesome</a>. Exclude the <code>fa fa-</code> prefix.</span>
  </div><br/>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/modes/_mode.html.erb
<div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="clearfix">
        <h4 class="pull-left"><i class="fa fa-<%= mode.icon %>"></i> <%= mode.name %></h4>
        <% if current_user&.has_role?(:admin) %>
          <h4 class="pull-right">
            <%= link_to edit_mode_path(mode) do %>
              <i class="fa fa-pencil fa-fw"></i>
            <% end %>
            <%= link_to destroy_mode_path(mode), remote: true, class: 'text-danger mode-delete', method: :delete do %>
              <i class="fa fa-times fa-fw"></i>
            <% end %>
          </h4>
        <% end %>
      </div>
      <p><%= mode.description %></p>
    </div>
  </div>
</div>

app/views/modes/edit.html.erb
<h1>Edit Travel Mode #<%= @mode.id %></h1>
<%= render 'form', url: update_mode_path(@mode) %>

app/views/modes/index.html.erb
<h1>Modes of Travel</h1>
<% if current_user&.has_role?(:admin) %>
  <p><%= link_to '+ Create mode', new_mode_path %></p>
<% end %>

<% @modes.in_groups_of(3).map(&:compact).each do |g| %>
  <div class="row">
    <% g.each do |m| %>
      <%= render 'mode', mode: m %>
    <% end %>
  </div>
<% end %>

app/views/modes/new.html.erb
<h1>New Travel Mode</h1>
<%= render 'form', url: create_mode_path %>